### ISSUE TITLE
поле itemprice0 должно содержать не более 2х цфир после запятой

### ISSUE THREAD

**Issue by Inkognitod** [Max1mCom/tinkoff-credit#1]
wordpress 5.3, woocommerce 3.8.1. выдает ошибку при нажатии на кнопку "поле itemprice0 должно содержать не более 2х цифр после запятой". в коде обнаружил такую историю:
input name="itemPrice_0" value="51377.777777777774" type="hidden"

**Comment by Max1mCom** [comment]
https://wordpress.org/support/topic/%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B0-%D0%BF%D0%BE%D0%BB%D1%8F-itemprice0/
